# SOURCES
# https://gist.github.com/mlisovyi/e8df5c907a8250e14cc1e5933ed53ffd

codes = {'Albania': 'AL',
 'Andorra': 'AD',
 'Austria': 'AT',
 'Belarus': 'BY',
 'Belgium': 'BE',
 'Bosnia and Herzegovina': 'BA',
 'Bulgaria': 'BG',
 'Croatia': 'HR',
 'Cyprus': 'CY',
 'Czech Republic': 'CZ',
 'Denmark': 'DK',
 'Estonia': 'EE',
 'Finland': 'FI',
 'France': 'FR',
 'Germany': 'DE',
 'Greece': 'GR',
 'Hungary': 'HU',
 'Iceland': 'IS',
 'Ireland': 'IE',
 'Italy': 'IT',
 'Kosovo': 'XK',
 'Latvia': 'LV',
 'Liechtenstein': 'LI',
 'Lithuania': 'LT',
 'Luxembourg': 'LU',
 'Macedonia': 'MK',
 'Malta': 'MT',
 'Moldova': 'MD',
 'Montenegro': 'ME',
 'Netherlands': 'NL',
 'Norway': 'NO',
 'Poland': 'PL',
 'Portugal': 'PT',
 'Romania': 'RO',
 'Russia': 'RU',
 'Serbia': 'RS',
 'Slovakia': 'SK',
 'Slovenia': 'SI',
 'Spain': 'ES',
 'Sweden': 'SE',
 'Switzerland': 'CH',
 'Ukraine': 'UA',
 'United Kingdom': 'GB'}